### PR TITLE
PointPerfect example using WIFI/IP/MQTT

### PR DESCRIPTION
**Pull request by mazgch**
Hi Nathan

This is a simple example demonstrating use of SSR corrections in SPARTN format from u-blox PointPerfect service. WiFi is used to connect to the server using MQTT protocol. 
 
Recommended Hardware:
MicroMod GNSS Carrier Board: https://www.sparkfun.com/products/17722 
ESP32 Micromod https://www.sparkfun.com/products/16781

Make sure the u-blox ZED-F9R GNSS receiver is running latest firmware (HPG 1.30) 
https://www.u-blox.com/en/product/zed-f9p-module?lang=de#tab-documentation-resources

### CODE REVIEW

**Comment by PaulZC** [comment]
Thank you Michael,

We will give this a quick test and then merge it into the library.

Very best wishes,
Paul & Nathan

**Comment by mazgch** [comment]
I am not seeing your issue in my setup, maybe because I have a different account at PointPerfect plan. I have evolved a bit the current working example. I will have some more PR to add support for NEO-D9S.

**Comment by PaulZC** [comment]
Hi Michael,

The issue I'm seeing - error -2 when _reconnecting_ to PointPerfect - is board package and compiler dependent.

I'm running your example on a SparkFun ESP32 Thing Plus - not MicroMod ESP32.

If I use the "SparkFun ESP32 Boards v1.0.1" (xtensa-esp32-elf-gcc  1.22.0-97-gc752ad5-5.2.0) then reconnecting works perfectly. If you are using MicroMod ESP32 then I think this is the same board package and compiler you are using?

But if I use the "Espressif Systems esp32 v2.0.2" (xtensa-esp32-elf-gcc  gcc8_4_0-esp-2021r2) then I get error -2 when I try to reconnect.

OK. I am not going to worry about this. But we may see issues raised by other users who run into the same problem.

I am working on improvements to the library to support the NEO-D9S and UBX-RXM-PMP. I should have an example for you to test tomorrow. My plan is to release a new version of the library - including your PointPerfect example - in the next few days.

Best wishes,
Paul

**Comment by mazgch** [comment]
Hi Paul,

I have a Lband example partly working with few issues I need still to look at. You can have a look at the example 18 and the required code changes for NEO-D9S to you library in my github. I worked around the PMP message callback issues by using wire directly. Maybe some of the library changes can go into your new release.

https://github.com/mazgch/SparkFun_u-blox_GNSS_Arduino_Library/tree/mazgch-band-pmp

regards,
Michael

**Pull request merged**
