### PR TITLE
add enable GNSS API (start / stop)

### PR DESCRIPTION
**Pull request by mazgch**

### CODE REVIEW

**Comment by PaulZC** [comment]
Thank you Michael (@mazgch ),

I'm working on v3 of the library - moving from UBX_CLASS_CFG to the configuration interface. I will probably merge this PR into the v3 branch.

Best wishes,
Paul

**Comment by mazgch** [comment]
Sore no problem

**Comment by PaulZC** [comment]
This is now in v3. It compiles OK but is currently untested...

**Comment by mazgch** [comment]
> This is now in v3. It compiles OK but is currently untested...

Nice, There is an opportunity to save flash by having helper function that is called from both softwareResetGNSSOnl and softwareEnableGNSS and some of the other similar functions. But I was not sure as this approach is are rely used in other places that have almost identical code.

**Comment by PaulZC** [comment]
Good suggestion! I've added that code in this commit: https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/commit/6613ec55b6ea0980e2358492f6c2349c6a7a34f0 . It compiles OK, but is currently untested.

**Comment by PaulZC** [comment]
Hi Michael (@mazgch ),

The v3 library is now public:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3

It is still Work-In-Progress. I'm slowly working my way through the examples, updating and testing each one as I go. But I'm confident the library is useable as-is. It does of course contain your ```softwareEnableGNSS``` code.

You won't be able to install it via the Arduino Library Manager. For now, you will need to download it and install it manually.

Please give it a try and let me know if you spot any problems. Thanks! If you do find a problem, please open an Issue here:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/issues

Very best wishes,
Paul

**Comment by PaulZC** [comment]
Closing - thanks! Please see:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/releases/tag/v3.0.0

**Pull request closed without merging**
