### PR TITLE
Fix compilation for AVR DA- and DB-series MCUs

### PR DESCRIPTION
**Pull request by nabelekt**

### CODE REVIEW

**Comment by PaulZC** [comment]
Hi Thomas (@nabelekt ),
Thank you for submitting this PR. Just for information, can you tell me which board package you are using? Is it DxCore?
Best wishes,
Paul

**Comment by nabelekt** [comment]
Yes, I am using DxCore.

Thanks.
Thomas

**Comment by PaulZC** [comment]
Hi Thomas (@nabelekt ),
Thanks again for this. Merging for testing... I think I may change this to ARDUINO_ARCH_MEGAAVR to cover both families in one go, but I will let you know.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi Thomas,
I am going with ARDUINO_ARCH_MEGAAVR. Please see [this commit](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/commit/9243493c9b2d8918c155e3199318b4242b85147b) for the changes. It covers both DA and DB in one go. I have tested it using IDE 1.8.13 on Windows - please check it on your platform. Thanks!
Best wishes,
Paul

**Pull request merged**
