### PR TITLE
getUnixEpoch() method added

### PR DESCRIPTION
**Pull request by UT2UH**
Unix Epoch time returned as uint32_t to cast to user provided time library 'time_t' type.

### CODE REVIEW

**Comment by PaulZC** [comment]
Hi @UT2UH ,
Thank you - this is much better. I will merge shortly. I just need to rename my Example24 first! ;-)
All the best,
Paul

**Comment by PaulZC** [comment]
Hi @UT2UH ,

I must admit, I think it might be a good idea to remove the confirmedTime check from getUnixEpoch. That way users of modules with older firmware will be able to use the function. Not all modules /protocol versions support time validity. What are your thoughts please?

@adamgarbo: I'm not worried about the function name. get UnixEpoch makes it clear it is the 1970 Epoch, not any of the other variants. But thanks for the reminder!

Best wishes,
Paul

**Comment by adamgarbo** [comment]
Would it also be possible to modify `.getUnixEpoch();` so as to make the microsecond argument optional? If I try to call the function without providing it with a variable to write to, I get the error:

```
/Users/adam/Documents/GitHub/Cryologger_Glacier_Velocity_Measurement_System/Software/cryologger_gvms_micromod_test/05_gnss.ino: In function 'void syncRtc()':
05_gnss:133:53: error: no matching function for call to 'SFE_UBLOX_GNSS::getUnixEpoch()'
         unsigned long gnssEpoch = gnss.getUnixEpoch(); // Get GNSS epoch time
                                                     ^
In file included from /Users/adam/Documents/GitHub/Cryologger_Glacier_Velocity_Measurement_System/Software/cryologger_gvms_micromod_test/cryologger_gvms_micromod_test.ino:20:
/Users/adam/Documents/Arduino/libraries/SparkFun_u-blox_GNSS_Arduino_Library/src/SparkFun_u-blox_GNSS_Arduino_Library.h:941:11: note: candidate: 'uint32_t SFE_UBLOX_GNSS::getUnixEpoch(uint32_t&, uint16_t)'
  uint32_t getUnixEpoch(uint32_t& microsecond, uint16_t maxWait = defaultMaxWait);
           ^~~~~~~~~~~~
/Users/adam/Documents/Arduino/libraries/SparkFun_u-blox_GNSS_Arduino_Library/src/SparkFun_u-blox_GNSS_Arduino_Library.h:941:11: note:   candidate expects 2 arguments, 0 provided
``` 

This would allow it to be called by users who aren't interested in microseconds.

Cheers,
Adam

**Comment by adamgarbo** [comment]
Thanks, @UT2UH!

**Pull request merged**
